/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class com_trychen_logitow_LogiTowBLEStack */

#ifndef _Included_com_trychen_logitow_LogiTowBLEStack
#define _Included_com_trychen_logitow_LogiTowBLEStack
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_trychen_logitow_LogiTowBLEStack
     * Method:    setup
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_com_trychen_logitow_LogiTowBLEStack_setup
    (JNIEnv *, jclass);
    
    /*
     * Class:     com_trychen_logitow_LogiTowBLEStack
     * Method:    getNativeBluetoothState
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_com_trychen_logitow_LogiTowBLEStack_getNativeBluetoothState
    (JNIEnv *, jclass);
    
    /*
     * Class:     com_trychen_logitow_LogiTowBLEStack
     * Method:    startScanDevice
     * Signature: ()Z
     */
    JNIEXPORT jboolean JNICALL Java_com_trychen_logitow_LogiTowBLEStack_startScanDevice
    (JNIEnv *, jclass);
    
    /*
     * Class:     com_trychen_logitow_LogiTowBLEStack
     * Method:    stopScanDevice
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_com_trychen_logitow_LogiTowBLEStack_stopScanDevice
    (JNIEnv *, jclass);
    
    /*
     * Class:     com_trychen_logitow_LogiTowBLEStack
     * Method:    disconnect
     * Signature: (Z)V
     */
    JNIEXPORT void JNICALL Java_com_trychen_logitow_LogiTowBLEStack_disconnect
    (JNIEnv *, jclass, jboolean);
    
#ifdef __cplusplus
}
#endif
#endif
